### ISSUE TITLE
composer install error 

### ISSUE THREAD

**Issue by izac1** [skiptirengu/yii2-places#2]
Problem 1
    - nevermnd/yii2-places v1.0.3 requires bower-asset/typeahead-addresspicker ^0.1.4 -> satisfiable by bower-asset/typeahead-addresspicker[0.1.4].
    - Installation request for nevermnd/yii2-places 1.0.3 -> satisfiable by nevermnd/yii2-places[v1.0.3].
    - Can only install one of: bower-asset/typeahead.js[v0.10.4, v0.11.1].
    - Can only install one of: bower-asset/typeahead.js[v0.10.4, v0.11.1].
    - Can only install one of: bower-asset/typeahead.js[v0.10.4, v0.11.1].
    - bower-asset/typeahead-addresspicker 0.1.4 requires bower-asset/typeahead.js ~0.10.4 -> satisfiable by bower-asset/typeahead.js[v0.10.5, v0.10.4].
    - Conclusion: don't install bower-asset/typeahead.js v0.10.5
    - Installation request for bower-asset/typeahead.js (locked at v0.11.1) -> satisfiable by bower-asset/typeahead.js[v0.11.1].

**Comment by skiptirengu** [comment]
Thank you for the report i'll look into it.

**Comment by skiptirengu** [comment]
Do you have `bower-asset/typeahead.js` added to your `require` section on your `composer.json`? If so, this plugin only works with <= 0.10.5 versions of typeahead.

**Comment by izac1** [comment]
@skiptirengu i dont have , but composer downlad `typeahead.js` but version new version , you have in  `"bower-asset/typeahead.js": "0.10.5 || ~0.10.0",`  and composer download new version , but `typeahead-addresspicker` dont support new version.

**Comment by skiptirengu** [comment]
Should be fixed, try version 1.0.4.

**Comment by izac1** [comment]
another problem  

> Problem 1
>     - Installation request for nevermnd/yii2-places 1.0.4 -> satisfiable by nevermnd/yii2-places[v1.0.4].
>     - nevermnd/yii2-places v1.0.4 requires bower-asset/typeahead-addresspicker dev-typeahead-0.11.1 as 0.1.4 -> no matching package found.

**Comment by izac1** [comment]
I have some solution , yii2-gii module use `typeahead.js` if we manual reinstall old version like 
`composer require bower-asset/typeahead.js:0.10.5` we can install you plugin
