### ISSUE TITLE
Missed css class

### ISSUE THREAD

**Issue by izac1** [skiptirengu/yii2-places#3]
When we create a `Html::textInput` give class only `<input type="text" id="w1" name="place" class="tt-input" autocomplete="off" spellcheck="false" dir="auto" style="position: relative;vertical-align: top;background-color: transparent;height: 33px;">` but in this page sgruhier.github.io/typeahead-addresspicker we see 2 class `<input id="address" class="typeahead tt-input" type="text" placeholder="Enter an address" autocomplete="off" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;">`
Missed typeahead  class

**Comment by izac1** [comment]
Fast dirty way solution , i think in 0.10.5 version , delete add class to `input`, so we have 2 way 
1) rewrite css
2)add to `buildTypeAhead` some code to add class like 
`return "$('#{$this->options['id']}').typeahead(null, " . Json::encode($options) . ");$('#{$this->options['id']}').addClass('typeahead');$('.tt-hint').addClass('typeahead')";`

**Comment by skiptirengu** [comment]
You can set input classes by configuring the options property. 
Ex:
 ```php
'options' => [
  'class' => ['typeahead', 'my-css-class']
]
```

Anyway, just added it by default, should be fixed on dev-master.
